<?php
use \Fisharebest\Webtrees\I18N;
use \Fisharebest\Webtrees\Theme;

namespace Fisharebest\Webtrees;
use \Fisharebest\Webtrees\Functions\FunctionsCharts;

global $WT_TREE;
$stats = new Stats($WT_TREE);

?>
<main id="content">
<div id="page-branch-statistics">
    <h2><?php echo $this->getPageTitle() ?></h2>

    <form name="people" method="get" action="?">
        <input type="hidden" name="ged" value="<?php echo $this->getTree()->getNameHtml() ?>">
        <input type="hidden" name="mod" value="branch_statistics">
        <table class="list_table">
            <tbody>
                <tr>
                    <td class="descriptionbox">
                        <label for="rootid"><?php echo I18N::translate('Individual') ?></label>
                    </td>
                    <td class="optionbox">
                        <input class="pedigree_form" data-autocomplete-type="INDI" type="text" name="rootid" id="rootid" size="3" value="<?php echo $this->root->getXref() ?>">
                        <?php echo $this->printFindIndividualLink() ?>
                    </td>
                    <td class="topbottombar vmiddle" colspan="2">
                    </td>
                </tr>
                <tr>
                <td class="descriptionbox">
                        <label for="generations"><?php echo I18N::translate('Number of generations') ?></label>
                    </td>
                    <td class="optionbox">
                        <?php echo $this->getGenerationsInputControl() ?>
                    </td>
                    <td class="topbottombar vmiddle" colspan="2">
                        <input type="submit" value="<?php echo $this->translate('view') ?>">
                    </td>
                </tr>
            </tbody>
        </table>
    </form>

<?php

$json = $this->jsonworker();
$parsed_json = json_decode($json);

$sum = [];
for ($i=1; $i<=$this->generations+1; $i++)
{
	$sum[$i] = 0;
}
$cloud = [];

$complet = 0;
$total = 0;
$totalmale = 0;
$totalfemale = 0;
$totaldead = 0;
$totalalive = 0;
$totalbirth = 0;
$name = "";
$generation_val = 0;
$epok = array();

$jsonIterator = new \RecursiveIteratorIterator(
    new \RecursiveArrayIterator($parsed_json->{'data'}));
foreach ($jsonIterator as $key => $val) {
    if(!is_array($val)) {
        switch ($key) {
            case 'generation':
                $sum[$val]++;
                $generation_val = $val;
                break;
            case 'complet':
                if ($val) { $complet++; }
                break;
            case 'name':
                $total++;
                $name = $val;
                
                if ($generation_val >= 16) { unset($sum[$val]); }
                break;
            case 'sex':
                if($val == "M") { $totalmale++; }
                if($val == "F") { $totalfemale++; }
                break;
            case 'dcd':
                if($val == "true")
                {
                    $totaldead++;
                }
                else
                {
                    $totalalive++;
                    $name_alive[] = $name;
                }
                break;
            case 'born':
                $date = explode("-",$val);
                if ($date[0] != " ")
                {
                    $totalbirth++;
                }
                if ($val != 0)
                {
                    $epok[$generation_val][] = $val;
                }
                break;
            case 'lieu':
                if ($val != "")
                {
                    if (isset($cloud[$val]))
                    {
                        $cloud[$val]++;
                    }
                    else
                    {
                        $cloud[$val] = 1;
                    }
                }
                break;
        }
    }
}
?>

<table class="facts_table">
    <thead>
        <tr>
            <th data-column-id=<?php echo I18N::translate("Generation") ?> data-type="numeric"><?php echo I18N::translate("Generation") ?></th>
            <th data-column-id=<?php echo I18N::translate("Total individuals") ?> data-type="numeric"><?php echo I18N::translate("Total individuals") ?></th>
            <th data-column-id=<?php echo I18N::translate("Total individuals (cumulative)") ?> data-type="numeric"><?php echo I18N::translate("Total individuals (cumulative)") ?></th>
            <th data-column-id=<?php echo I18N::translate("Time of life") ?> data-type="numeric"><?php echo I18N::translate("Time of life") ?></th>
            <th data-column-id=<?php echo I18N::translate("Ancestors") ?>><?php echo I18N::translate("Ancestors") ?></th>
	 </tr>
    </thead>
    <tbody>

    <?php
    $indi=1;
    $total_indi = 1;
    $total = 0;
    
    for ($i=1; $i<=$this->generations+1; $i++)
    {
        //break if there are no more individuals
        if ($sum[$i] == 0)
        {
            break;
        }
        // calculating the median birth dates
        $epoque = $this->calculate_median($epok[$i],50);
        switch ($i) {
            case '1':
                $relationship = I18N::translate('self');
                break;
            case '2':
                $relationship = I18N::translate('Parents');
                break;
            case '3':
                $relationship = I18N::translateContext('parent’s parent', 'grandparent');
                break;
            case '4':
                $relationship = I18N::translateContext('parent’s parent’s parent', 'great-grandparent');
                break;
            default:
                $relationship = I18N::translate('great ×%s grandparent', I18N::number($i - 1));
                break;
        }
        
        //$relationship = FunctionsCharts::getSosaName($i + 2);
        $total = $total + $sum[$i];
        if ($total_indi == 1) {
            $text_total_indi = I18N::translate('Individual');
        } else {
            $text_total_indi = I18N::translate('Individuals');
        }
        echo '
        <tr class="facts_value"><td>'.$i.'</td>
        <td><meter min="0" optimum="'.$indi.'" low="'.($indi/4).'" high="'.($indi/2).'" max="'.$indi.'" value="'.$sum[$i].'"></meter> '.$sum[$i].'/'.$indi.'</td>
        <td>'.$total .'/'. ($total_indi).' '.$text_total_indi .'</td>
        <td>'.$epoque.'</td>
        <td>'.$relationship;
        echo '</td></tr>';
        $indi = $indi+$indi;

        $total_indi = $total_indi + $indi;
    }

?>

    </tbody>
</table>
<br>
<table class="facts_value">
    <thead>
        <tr class="facts_value">
            <th data-column-id=<?php echo I18N::translate("Number of complete / found individuals") ?> data-type="numeric"><?php echo I18N::translate("Number of complete / found individuals") ?></th>
            <th data-column-id=<?php echo I18N::translate("Total males") ?> data-type="numeric"><?php echo I18N::translate("Total males") ?></th>
            <th data-column-id=<?php echo I18N::translate("Total females") ?> data-type="numeric"><?php echo I18N::translate("Total females") ?></th>
            <th data-column-id=<?php echo I18N::translate("Total dead") ?> data-type="numeric"><?php echo I18N::translate("Total dead") ?></th>
            <th data-column-id=<?php echo I18N::translate("Total living") ?> data-type="numeric"><?php echo I18N::translate("Total living") ?></th>
            <th data-column-id=<?php echo I18N::translate("Total births") ?> data-type="numeric"><?php echo I18N::translate("Total births") ?></th>
	 </tr>
    </thead>
    <tbody>
		<tr>
		<td class="facts_value"><meter min="0" low="<?php echo $total/4;?>" high="<?php echo $total/2;?>" optimum="<?php echo $total;?>" max="<?php echo $total;?>" value="<?php echo $sum[$parsed_json->{'generations'}];?>"></meter><?php echo " ".$complet."/". $total.""; ?></td>
		<td class="facts_value branchs-statistics-page"><?php echo $totalmale;?></td>
		<td class="facts_value branchs-statistics-page"><?php echo $totalfemale;?></td>
		<td class="facts_value branchs-statistics-page"><?php echo $totaldead;?></td>
		<td class="facts_value branchs-statistics-page"><?php echo $totalalive;?></td>
		<td class="facts_value branchs-statistics-page"><?php echo $totalbirth;?></td>
		</tr>
    </tbody>
</table>
<?php
echo "<p><br>".I18N::translate("Total living")." :</br>";
foreach ($name_alive as $key => $value) {
    echo ($key+1).' : '.$value.'<br>';
}
echo '</p></main>';
